#!/usr/bin/env bash
# install ngix server

apt-get -y update
apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://youtu.be/q5m09rqOoxE permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a \\terror_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx restart
